name: Publish Package to NPM

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  release:
    types: [created]  # Trigger on release creation

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Check out the repository
      - uses: actions/setup-node@v3  # Set up Node.js
        with:
          node-version: '18.x'  # Specify Node.js version
          registry-url: 'https://registry.npmjs.org'  # NPM registry URL
      
      - name: Install dependencies
        run: npm install  # Use npm install to create package-lock.json if it doesn't exist
      
      - name: Run tests
        run: npm test  # Run tests
      
      - name: Build
        run: npm run build  # Build the project
      
      - name: Publish Package to NPM
        run: npm publish  # Publish package to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Provide NPM token for authentication
